version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4
  cypress: cypress-io/cypress@1

jobs:
  install:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      - run:
          name: build
          command: npm run build
      - save_cache:
          key: build-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./public
  test:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      - run: npm run test:cover
      - codecov/upload:
          file: ./coverage/lcov.info
      - store_artifacts:
          path: ./coverage/lcov.info
  lint:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: npm run lint

workflows:
  build:
    jobs:
      - install
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
      - cypress/run:
          requires:
            - install
            - build
          start: "npm run serve"
