version: 2.1

jobs:
  test:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: npm ci
      - run: npm test
  lint:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint

workflows:
  build:
    jobs:
      - test
      - lint
